# NAIVE BAYES

In [51]:
# On importe les librairies
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB,MultinomialNB,CategoricalNB

In [52]:
# On importe le dataset
f="/content/REM_NREM_15f.csv"
dataset = pd.read_csv(f)
dataset.head()

  Sleep_Stage  PeakF_Beta_F4  ...  PeakF_Delta_F4  Spectral Edge_Alpha_C4
0        NREM       14.36098  ...         0.74927                17.73268
1        NREM       16.60878  ...         0.62439                18.98146
2        NREM       14.98537  ...         0.37463                16.60878
3        NREM       11.36390  ...         0.99902                16.10927
4        NREM       15.98439  ...         2.87220                15.11024

[5 rows x 16 columns]

In [53]:
# On sépare notre dataframe en deux les inputs et les targets ( survived )
X = dataset.drop('Sleep_Stage',axis='columns')
Y = dataset.Sleep_Stage

In [54]:
# Identifier les colonnes ou il manque des données
X.columns[X.isna().any()]

Index([], dtype='object')

In [55]:
X.describe()

       PeakF_Beta_F4  PeakF_Beta_C4  ...  PeakF_Delta_F4  Spectral Edge_Alpha_C4
count    89096.00000   89096.000000  ...    89096.000000            89096.000000
mean        20.65046      21.629436  ...        1.233448               14.857811
std         19.37498      19.543395  ...        3.660213                5.263334
min          3.87122       3.871220  ...        0.124880                0.124880
25%         10.73951      11.239020  ...        0.499510               13.237070
50%         12.61268      13.611710  ...        0.749270               14.236100
75%         17.85756      18.357070  ...        0.999020               15.360000
max        127.87512     127.875120  ...       31.968780               50.076100

[8 rows x 15 columns]

In [56]:
X.fillna(X.mean(), inplace=True)
X.describe()

       PeakF_Beta_F4  PeakF_Beta_C4  ...  PeakF_Delta_F4  Spectral Edge_Alpha_C4
count    89096.00000   89096.000000  ...    89096.000000            89096.000000
mean        20.65046      21.629436  ...        1.233448               14.857811
std         19.37498      19.543395  ...        3.660213                5.263334
min          3.87122       3.871220  ...        0.124880                0.124880
25%         10.73951      11.239020  ...        0.499510               13.237070
50%         12.61268      13.611710  ...        0.749270               14.236100
75%         17.85756      18.357070  ...        0.999020               15.360000
max        127.87512     127.875120  ...       31.968780               50.076100

[8 rows x 15 columns]

In [57]:
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.2)

In [58]:
model = CategoricalNB()

In [59]:
model.fit(X_train,y_train)

CategoricalNB()

In [60]:

print(f)
print(model.score(X_train,y_train))

/content/REM_NREM_15f.csv
0.7291654975026657